### ISSUE TITLE
Map not centered on the marker

### ISSUE THREAD

**Issue by RCatersels** [mendix/GoogleMapsWidget#12]
I noticed that the map is not centered on the single marker. In our model we have a map with a height of 220 and pan to context set to yes, but the marker is just outside the map. 

Regards,

Ronald

**Comment by JelteMX** [comment]
Do you have this map in a Groupbox or Tab Container? While doing another bugfix today I noticed this behaviour in a Tab Container. I have a possible solution for it, but I need to test this a little bit further. I added this as a [TODO in a current bugfix branch](https://github.com/mendix/GoogleMapsWidget/blob/bugfix/ticket-465876-association/src/GoogleMaps/widget/GoogleMaps.js#L78))

(My solution: it will do a gotocontext on resize, because resize is called when opening a tabcontainer. This also means that the map wil jump to that marker every time you resize the window, which may or may not be appropriate behaviour)
